name: page_promociones_-_filtros
timestamp: 1498468593
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1465201940
positions: {  }
sections:
  header: Header
  navigation: Navigation
  postnavigation: Postnavigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  prefooter: Prefooter
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-1442: Custom
    custom-4606: 'Custom HTML'
    custom-8312: 'Custom HTML'
    custom-1418: 'Custom HTML'
    custom-6643: 'Custom HTML'
    custom-1258: 'Custom HTML'
    custom-4054: 'Custom HTML'
  menu:
    menu-6657: Menu
    menu-8007: Menu
    menu-4064: Menu
  logo:
    logo-4749: 'Logo / Image'
    logo-2859: 'Logo / Image'
    logo-9981: 'Logo / Image'
  chef_search:
    chef_search-8317: 'Chef Search'
    chef_search-8850: 'Chef Search'
  modal-login:
    modal-login-2554: 'Modal Login'
    modal-login-5361: 'Modal Login'
    modal-login-9818: 'Modal Login'
  content:
    system-content-1775: 'Page Content'
  slideshow:
    slideshow-5028: Slideshow
  social:
    social-9875: Social
  mobile-menu:
    mobile-menu-9260: 'Mobile Menu'
  spacer:
    spacer-1318: Spacer
    spacer-2255: Spacer
  totop:
    totop-3790: 'To Top'
inherit:
  pages:
    header: header
    navigation: navigation
    custom-1442: custom-3022
    showcase: showcase
    feature: feature
    main: main
    subfeature: subfeature
    footer: footer
    offcanvas: offcanvas
    logo-4749: logo-6922
    menu-8007: menu-8101
    chef_search-8317: chef_search-3140
    custom-4606: custom-3320
    modal-login-2554: modal-login-4598
    logo-2859: logo-4062
    menu-4064: menu-7976
    custom-8312: custom-6133
    modal-login-5361: modal-login-2830
    chef_search-8850: chef_search-6337
    modal-login-9818: modal-login-8521
    system-content-1775: system-content-6416
    slideshow-5028: slideshow-3373
    logo-9981: logo-6178
    social-9875: social-4968
    mobile-menu-9260: mobile-menu-5891
  home:
    prefooter: prefooter
    custom-1418: custom-8930
    custom-6643: custom-2913
    custom-1258: custom-2737
    custom-4054: custom-8499
    spacer-1318: spacer-4674
    totop-3790: totop-2079
    spacer-2255: spacer-5099
