version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1467015210
layout:
  header: {  }
  navigation: {  }
  /postnavigation/:
    -
      - custom-3993
  /premain/: {  }
  /container-main/:
    -
      -
        '/main/ 75':
          -
            - chef_profile-8269
      -
        'sidebar 25':
          -
            - chef_sidebar_perfil-9283
  /main-mobile/: {  }
  /prefooter/:
    -
      - 'custom-2590 15'
      - 'custom-1188 15'
      - 'custom-1430 25'
      - 'custom-3397 45'
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: pages
      include:
        - children
        - attributes
  postnavigation:
    type: section
    attributes:
      boxed: '0'
      class: ''
      extra:
        -
          style: 'background-color:#dadada'
  premain:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#EDEDED'
  main:
    attributes:
      boxed: ''
      class: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#f5f5f5'
  main-mobile:
    title: Mobile
    attributes:
      boxed: '2'
      class: 'visible-phone visible-tablet'
      extra:
        -
          style: 'background-color:#f5f5f5'
  prefooter:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#e9e9e9'
  footer:
    inherit:
      outline: pages
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
content:
  custom-3993:
    title: 'Custom HTML'
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
      particle: custom-3022
  chef_profile-8269:
    title: 'Chef Profile'
  chef_sidebar_perfil-9283:
    title: 'Chef Sidebar Perfil'
  custom-2590:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
      particle: custom-8930
  custom-1188:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
      particle: custom-2913
  custom-1430:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
      particle: custom-2737
  custom-3397:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
      particle: custom-8499
