version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1467015210
layout:
  header: {  }
  navigation: {  }
  postnavigation: {  }
  /premain/:
    -
      - custom-9761
  /container-main/:
    -
      -
        '/main/ 75':
          -
            - system-content-9195
      -
        'sidebar 25': {  }
  main-mobile: {  }
  prefooter: {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - children
  postnavigation:
    type: section
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
  premain:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#EDEDED'
  main:
    attributes:
      boxed: ''
      class: ''
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#f5f5f5'
  main-mobile:
    title: Mobile
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
  prefooter:
    type: section
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: pages
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
        - children
content:
  custom-9761:
    title: 'Custom HTML'
    attributes:
      html: "{% set post_empleo = function('get_post') %}\n{% set post_empleo_meta = function ('get_post_meta',post_empleo.ID) %}\n{% set current_user = function ('wp_get_current_user') %}\n<div class=\"promos-header\">\n    <h1>{{ post_empleo.post_title }}</h1>\n    <div class=\"deco-ball-bk\"></div>\n    <div class=\"gap-20\"></div>\n    <p class=\"recetas-header\">{{ post_empleo.post_excerpt }}</p>\n    <div class=\"gap-10\"></div>\n    <span class=\"prof\">{{post_empleo_meta['acf-field-puesto'][0]}}</span>\n    <div class=\"gap-10\"></div>\n    <p class=\"small ciudad\">{{post_empleo_meta['acf-ciudad'][0]}}, \n{{post_empleo_meta['acf-pais'][0]}}</p>\n{{post_empleo_meta['acf-fecha-inicio-convocatoria'][0]|date('d-m-Y')}} &nbsp;&nbsp;{{post_empleo_meta['acf-fecha-fin-convocatoria'][0]|date('d-m-Y')}}<br><br>\n    {% if function('is_user_logged_in') == 1  %} \n {% if current_user.data.ID == post_empleo.post_author %}\n    <a href=\"/listado-empleos-publicados\" class=\"btn btn-default btn-primary\">\n        <i class=\"fa fa-pencil c-w\"></i> Editar oferta\n    </a>\n    <div class=\"gap-20\"></div>\n    {% endif %}\n{% endif %}\n    <div class=\"col-md-3\">\n    <div class=\"gap-20\"></div>\n    <div class=\"clear\"></div>\n    <div class=\"gap-10\"></div>\n    </div>\n</div>"
      twig: '1'
      filter: '1'
  system-content-9195:
    inherit:
      outline: post_-_recetas
      include:
        - attributes
        - block
      particle: system-content-7284
