version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1465201940
layout:
  header: {  }
  navigation: {  }
  postnavigation: {  }
  showcase: {  }
  /feature/:
    -
      - system-content-1135
    -
      - custom-4891
  main: {  }
  subfeature: {  }
  prefooter: {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  postnavigation:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  showcase:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  feature:
    type: section
    attributes:
      boxed: ''
      class: chefs-page
  main:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  subfeature:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  prefooter:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
content:
  custom-4891:
    title: 'Custom HTML'
    attributes:
      enabled: 0
      html: "{% set wp_user_chefs = function('get_users') %}\n\n<div class=\"g-content-array g-wordpress-posts{% if particle.css.class %} {{ particle.css.class }}{% endif %}\" {% if particle.extra %}{{ attr_extra|raw }}{% endif %}>\n    <div class=\"g-grid grid-chefs\">\n            \n    {% for wp_user_chef in wp_user_chefs %}\n        {% set wp_user_chef_data = function ('get_user_meta',wp_user_chef.data.ID) %}\n        \n        {% if wp_user_chef_data._chef_personal_photo[0] != '' %} {% set personal_photo_chef = function('site_url',wp_user_chef_data._chef_personal_photo[0]) %} {% else %} {% set personal_photo_chef = function ('site_url','/wp-content/uploads/users/user.jpg') %} {% endif %}\n        {% if wp_user_chef_data._chef_business_photo[0] != '' %} {% set business_photo_chef = function('site_url',wp_user_chef_data._chef_business_photo[0]) %} {% else %} {% set business_photo_chef = function ('site_url','/wp-content/uploads/users/logosombrero.png') %} {% endif %}\n        {% if wp_user_chef_data.first_name[0] != '' %} {% set nombre_chef = wp_user_chef_data.first_name[0] %} {% else %} {% set nombre_chef = 'Nombre' %} {% endif %}\n        {% if wp_user_chef_data._chef_city[0] != '' %} {% set ciudad_chef = wp_user_chef_data._chef_city[0] %} {% else %} {% set ciudad_chef = 'Ciudad' %} {% endif %}\n        {% if wp_user_chef_data._chef_country[0] != '' %} {% set pais_chef = wp_user_chef_data._chef_country[0] %} {% else %} {% set pais_chef = 'País' %} {% endif %}\n        {% if wp_user_chef_data._chef_busi_name[0] != '' %} {% set business_chef = wp_user_chef_data._chef_busi_name[0] %} {% else %} {% set business_chef = 'Nombre' %} {% endif %}\n        {% if wp_user_chef_data._chef_visits[0] != '' %} {% set visitas = wp_user_chef_data._chef_visits[0] %} {% else %} {% set visitas = '0' %} {% endif %}\n        {% if wp_user_chef_data.wpfui2i_featured_user[0] != 'yes' %} {% set destacado = false %} {% else %} {% set destacado = true %} {% endif %}\n        \n        \n        \n        {# Contamos el nuemro de seguidores #}\n        {% set users = function('get_users') %}\n        {% set cont_seguidores = 0 %}\n        {% for user in users %}\n            {% set user_data = function ('get_user_meta',user.data.ID) %}\n            {% set following = user_data._chef_follow[0]|json_decode %}\n            \n            {% if wp_user_chef.data.ID in following %}\n                {% set cont_seguidores = cont_seguidores + 1 %}\n            {% endif%}\n        {% endfor %}\n\n            <div class=\"chef-container\">\n                <div class=\"g-content\">\n                    {# Si es un user destacado #}\n                    {% if destacado == true %}\n                        {# <div>clase new</div> #}\n                    {% endif %}\n                    \n                    <div class=\"g-array-item std-box\">\n                            <a href=\"{{function ('site_url','mi-perfil/?perfil='~wp_user_chef.data.ID)}}\"><div class=\"img-box\" style=\"background-image:url('{{ business_photo_chef }}');\">\n\n                            </div></a>\n                        <div class=\"autor-img-box-sidebar\">\n                            <a href=\"{{function ('site_url','mi-perfil/?perfil='~wp_user_chef.data.ID)}}\"><img src=\"{{personal_photo_chef}}\"></a>\n                        </div>\n                        <div class=\"content-box-chefs text-center\">\n\n                            <h3><a href=\"{{function ('site_url','mi-perfil/?perfil='~wp_user_chef.data.ID)}}\">{{nombre_chef}}</a></h3>\n                            <p class=\"small ciudad\">{{ciudad_chef}}, {{pais_chef}}</p>\n                            <p>{{business_chef}}</p>\n\n                        </div>\n                            \n                        <div class=\"text-center\">\n                            <a class=\"read-more\" href=\"mi-perfil/?perfil={{wp_user_chef.data.ID}}\"><i class=\"fa fa-plus-circle fa-3x\" aria-hidden=\"true\"></i></a>\n                            <div class=\"gap-20\"></div>                                    \n                        </div>\n                        <div class=\"bottom-box\">\n                            <p class=\"\">&nbsp;\n                                <!--<i class=\"fa fa-thumbs-o-up\" aria-hidden=\"true\"></i> 96% (100) &nbsp; \n                                <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> 1200 &nbsp; -->\n                                <i class=\"fa fa-eye\" aria-hidden=\"true\"></i>{{visitas}}  &nbsp;\n                                <i class=\"fa fa-star\" aria-hidden=\"true\"></i>{{cont_seguidores}} &nbsp;             \n                            </p>\n                        </div>\n                    </div>\n                </div>\n            </div>\n    {% endfor %}\n    </div>\n\n</div>"
      twig: '1'
      filter: '1'
