version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1465201940
layout:
  /header/: {  }
  navigation: {  }
  /postnavigation/: {  }
  /showcase/: {  }
  /feature/: {  }
  /main/:
    -
      - system-content-9690
  subfeature: {  }
  prefooter: {  }
  footer: {  }
  offcanvas:
    -
      - mobile-menu-2705
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - children
  postnavigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#dadada'
  showcase:
    type: section
    attributes:
      boxed: '2'
      class: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - children
  prefooter:
    type: section
    inherit:
      outline: home
      include:
        - attributes
        - children
  footer:
    inherit:
      outline: pages
      include:
        - attributes
        - children
