ordering:
  que-se-cuece: ''
  talleres: ''
  recetas: ''
  promociones: ''
  m:
    foro: ''
    contacto: ''
    chefs: ''
    ayuda: ''
items:
  que-se-cuece:
    id: 52
    type: post_type
    enabled: true
    anchor_class: ''
  talleres:
    id: 53
    type: post_type
    enabled: true
    anchor_class: ''
  recetas:
    id: 54
    type: post_type
    enabled: true
    anchor_class: ''
  promociones:
    id: 55
    type: post_type
    enabled: true
    anchor_class: ''
  m:
    id: 126
    type: separator
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    icon: 'fa fa-navicon'
    icon_only: '1'
    columns:
      - 100
    anchor_class: ''
  m/foro:
    id: 1185
    type: custom
    enabled: true
    anchor_class: ''
  m/chefs:
    id: 455
    type: post_type
    enabled: true
    anchor_class: ''
  m/contacto:
    id: 59
    type: post_type
    enabled: true
    anchor_class: ''
  m/ayuda:
    id: 61
    type: post_type
    enabled: true
    anchor_class: ''
