version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1467015210
layout:
  /header/:
    -
      - 'logo-6997 30'
      - 'spacer-3668 70'
  /main/:
    -
      - system-messages-5169
    -
      - system-content-3845
  /footer/:
    -
      - position-footer
    -
      - 'copyright-7895 40'
      - 'spacer-3543 30'
      - 'branding-7035 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
