name: post_-_noticias
timestamp: 1490607573
version: 7
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1467015210
positions: {  }
sections:
  header: Header
  navigation: Navigation
  postnavigation: Postnavigation
  prefooter: Prefooter
  main: Main
  main-mobile: Mobile
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-3022: 'Custom HTML'
    custom-8930: 'Custom HTML'
    custom-2913: 'Custom HTML'
    custom-2737: 'Custom HTML'
    custom-8499: 'Custom HTML'
    custom-5623: 'Custom HTML'
    custom-9051: 'Custom HTML'
  content:
    system-content-7284: 'Page Content'
    system-content-3611: 'Page Content'
  chef_sidebar:
    chef_sidebar-7275: 'Chef Sidebar'
    chef_sidebar-3012: 'Chef Sidebar'
  spacer:
    spacer-4674: Spacer
    spacer-5099: Spacer
  totop:
    totop-2079: 'To Top'
  logo:
    logo-6178: Logo
    logo-6834: 'Logo / Image'
    logo-4155: 'Logo / Image'
  social:
    social-4968: Social
  mobile-menu:
    mobile-menu-5916: Mobile-menu
  menu:
    menu-5163: Menu
    menu-3876: Menu
  chef_search:
    chef_search-3431: 'Chef Search'
    chef_search-1241: 'Chef Search'
  modal-login:
    modal-login-2078: 'Modal Login'
    modal-login-4069: 'Modal Login'
    modal-login-5989: 'Modal Login'
inherit:
  pages:
    navigation: navigation
    logo-6834: logo-6922
    menu-5163: menu-8101
    chef_search-3431: chef_search-3140
    custom-5623: custom-3320
    modal-login-2078: modal-login-4598
    logo-4155: logo-4062
    menu-3876: menu-7976
    custom-9051: custom-6133
    modal-login-4069: modal-login-2830
    chef_search-1241: chef_search-6337
    modal-login-5989: modal-login-8521
