version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1465201940
layout:
  header: {  }
  navigation: {  }
  /postnavigation/:
    -
      - 'custom-2811 30'
      - 'menu-6505 70'
  showcase: {  }
  feature: {  }
  main: {  }
  subfeature: {  }
  prefooter: {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  postnavigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      extra:
        -
          style: 'background-color:#dadada'
  showcase:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  feature:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  main:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  subfeature:
    type: section
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  prefooter:
    type: section
    inherit:
      outline: home
      include:
        - attributes
        - children
  footer:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: pages
      include:
        - attributes
        - block
        - children
content:
  custom-2811:
    inherit:
      outline: pages
      include:
        - attributes
        - block
      particle: custom-3022
  menu-6505:
    attributes:
      menu: noticias-filtros
    block:
      class: filtros
