name: forms
timestamp: 1490607573
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1465201940
positions: {  }
sections:
  header: Header
  navigation: Navigation
  postnavigation: Postnavigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  prefooter: Prefooter
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-4549: Custom
    custom-6124: 'Custom HTML'
    custom-3461: 'Custom HTML'
    custom-3379: 'Custom HTML'
    custom-2810: 'Custom HTML'
    custom-8498: 'Custom HTML'
    custom-4677: 'Custom HTML'
  content:
    system-content-5498: 'Page Content'
  chef_sidebar_perfil:
    chef_sidebar_perfil-2701: 'Chef Sidebar Perfil'
  logo:
    logo-7584: 'Logo / Image'
    logo-5866: 'Logo / Image'
    logo-2560: 'Logo / Image'
  menu:
    menu-6442: Menu
    menu-5213: Menu
  chef_search:
    chef_search-6842: 'Chef Search'
    chef_search-5886: 'Chef Search'
  modal-login:
    modal-login-4456: 'Modal Login'
    modal-login-2983: 'Modal Login'
    modal-login-8916: 'Modal Login'
  slideshow:
    slideshow-2425: Slideshow
  social:
    social-3258: Social
  mobile-menu:
    mobile-menu-6786: 'Mobile Menu'
  spacer:
    spacer-7727: Spacer
    spacer-4377: Spacer
  totop:
    totop-1833: 'To Top'
inherit:
  pages:
    navigation: navigation
    custom-4549: custom-3022
    showcase: showcase
    main: main
    subfeature: subfeature
    footer: footer
    offcanvas: offcanvas
    logo-7584: logo-6922
    menu-6442: menu-8101
    chef_search-6842: chef_search-3140
    custom-6124: custom-3320
    modal-login-4456: modal-login-4598
    logo-5866: logo-4062
    menu-5213: menu-7976
    custom-3461: custom-6133
    modal-login-2983: modal-login-2830
    chef_search-5886: chef_search-6337
    modal-login-8916: modal-login-8521
    slideshow-2425: slideshow-3373
    logo-2560: logo-6178
    social-3258: social-4968
    mobile-menu-6786: mobile-menu-5891
  home:
    prefooter: prefooter
    custom-3379: custom-8930
    custom-2810: custom-2913
    custom-8498: custom-2737
    custom-4677: custom-8499
    spacer-7727: spacer-4674
    totop-1833: totop-2079
    spacer-4377: spacer-5099
