name: post_-_empleo
timestamp: 1496835819
version: 7
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: 2_column_-_right
  timestamp: 1467015210
positions: {  }
sections:
  header: Header
  navigation: Navigation
  postnavigation: Postnavigation
  prefooter: Prefooter
  sidebar: Sidebar
  main-mobile: Mobile
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-2541: 'Custom HTML'
    custom-4375: 'Custom HTML'
    custom-1072: 'Custom HTML'
    custom-5106: 'Custom HTML'
    custom-6622: 'Custom HTML'
    custom-8697: 'Custom HTML'
    custom-5974: 'Custom HTML'
  content:
    system-content-9655: 'Page Content'
    system-content-4793: 'Page Content'
  chef_sidebar:
    chef_sidebar-7316: 'Chef Sidebar'
    chef_sidebar-7912: 'Chef Sidebar'
  spacer:
    spacer-7459: Spacer
    spacer-7236: Spacer
  totop:
    totop-9929: 'To Top'
  mobile-menu:
    mobile-menu-6300: Mobile-menu
  logo:
    logo-6901: 'Logo / Image'
    logo-9851: 'Logo / Image'
    logo-4746: 'Logo / Image'
  menu:
    menu-6771: Menu
    menu-4118: Menu
  chef_search:
    chef_search-4521: 'Chef Search'
    chef_search-1117: 'Chef Search'
  modal-login:
    modal-login-4613: 'Modal Login'
    modal-login-1722: 'Modal Login'
    modal-login-1874: 'Modal Login'
  social:
    social-6443: Social
inherit:
  post_-_noticias:
    header: header
    postnavigation: postnavigation
    sidebar: sidebar
    main-mobile: main-mobile
    prefooter: prefooter
    offcanvas: offcanvas
    custom-2541: custom-3022
    system-content-9655: system-content-3611
    chef_sidebar-7316: chef_sidebar-7275
    system-content-4793: system-content-9178
    chef_sidebar-7912: chef_sidebar-3012
    custom-4375: custom-8930
    custom-1072: custom-2913
    custom-5106: custom-2737
    custom-6622: custom-8499
    spacer-7459: spacer-4674
    totop-9929: totop-2079
    spacer-7236: spacer-5099
    mobile-menu-6300: mobile-menu-5916
  pages:
    navigation: navigation
    footer: footer
    logo-6901: logo-6922
    menu-6771: menu-8101
    chef_search-4521: chef_search-3140
    custom-8697: custom-3320
    modal-login-4613: modal-login-4598
    logo-9851: logo-4062
    menu-4118: menu-7976
    custom-5974: custom-6133
    modal-login-1722: modal-login-2830
    chef_search-1117: chef_search-6337
    modal-login-1874: modal-login-8521
    logo-4746: logo-6178
    social-6443: social-4968
