context: {  }
menu: {  }
post:
  page:
    268: true
    31: true
    24: true
    270: true
    25: true
    473: true
taxonomy: {  }
archive:
  product_cat:
    163: true
woocommerce:
  -
    is_product: true
    is_cart: true
buddypress: {  }
